// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/genre.proto

package genre

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenreData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenreData) Reset() {
	*x = GenreData{}
	mi := &file_proto_genre_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenreData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenreData) ProtoMessage() {}

func (x *GenreData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_genre_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenreData.ProtoReflect.Descriptor instead.
func (*GenreData) Descriptor() ([]byte, []int) {
	return file_proto_genre_proto_rawDescGZIP(), []int{0}
}

func (x *GenreData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GenreData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GenreData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GenreData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// Изменённый GetAllRequest с параметрами пагинации.
type GetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNumber    int32                  `protobuf:"varint,1,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"` // номер страницы, начиная с 1
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`       // количество элементов на странице
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_proto_genre_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_genre_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_proto_genre_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *GetAllRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Изменённый GetAllResponse с общим количеством элементов.
type GetAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Genres        []*GenreData           `protobuf:"bytes,1,rep,name=genres,proto3" json:"genres,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	TotalPages    int32                  `protobuf:"varint,3,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	mi := &file_proto_genre_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_genre_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse.ProtoReflect.Descriptor instead.
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return file_proto_genre_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllResponse) GetGenres() []*GenreData {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *GetAllResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetAllResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type GetGenreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GenreId       string                 `protobuf:"bytes,1,opt,name=genre_id,json=genreId,proto3" json:"genre_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGenreRequest) Reset() {
	*x = GetGenreRequest{}
	mi := &file_proto_genre_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGenreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenreRequest) ProtoMessage() {}

func (x *GetGenreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_genre_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenreRequest.ProtoReflect.Descriptor instead.
func (*GetGenreRequest) Descriptor() ([]byte, []int) {
	return file_proto_genre_proto_rawDescGZIP(), []int{3}
}

func (x *GetGenreRequest) GetGenreId() string {
	if x != nil {
		return x.GenreId
	}
	return ""
}

type GetGenreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Genre         *GenreData             `protobuf:"bytes,1,opt,name=genre,proto3" json:"genre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGenreResponse) Reset() {
	*x = GetGenreResponse{}
	mi := &file_proto_genre_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGenreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenreResponse) ProtoMessage() {}

func (x *GetGenreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_genre_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenreResponse.ProtoReflect.Descriptor instead.
func (*GetGenreResponse) Descriptor() ([]byte, []int) {
	return file_proto_genre_proto_rawDescGZIP(), []int{4}
}

func (x *GetGenreResponse) GetGenre() *GenreData {
	if x != nil {
		return x.Genre
	}
	return nil
}

type CreateGenreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGenreRequest) Reset() {
	*x = CreateGenreRequest{}
	mi := &file_proto_genre_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGenreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGenreRequest) ProtoMessage() {}

func (x *CreateGenreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_genre_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGenreRequest.ProtoReflect.Descriptor instead.
func (*CreateGenreRequest) Descriptor() ([]byte, []int) {
	return file_proto_genre_proto_rawDescGZIP(), []int{5}
}

func (x *CreateGenreRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGenreRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateGenreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Genre         *GenreData             `protobuf:"bytes,1,opt,name=genre,proto3" json:"genre,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGenreResponse) Reset() {
	*x = CreateGenreResponse{}
	mi := &file_proto_genre_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGenreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGenreResponse) ProtoMessage() {}

func (x *CreateGenreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_genre_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGenreResponse.ProtoReflect.Descriptor instead.
func (*CreateGenreResponse) Descriptor() ([]byte, []int) {
	return file_proto_genre_proto_rawDescGZIP(), []int{6}
}

func (x *CreateGenreResponse) GetGenre() *GenreData {
	if x != nil {
		return x.Genre
	}
	return nil
}

func (x *CreateGenreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateGenreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GenreId       string                 `protobuf:"bytes,1,opt,name=genre_id,json=genreId,proto3" json:"genre_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGenreRequest) Reset() {
	*x = UpdateGenreRequest{}
	mi := &file_proto_genre_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGenreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGenreRequest) ProtoMessage() {}

func (x *UpdateGenreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_genre_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGenreRequest.ProtoReflect.Descriptor instead.
func (*UpdateGenreRequest) Descriptor() ([]byte, []int) {
	return file_proto_genre_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateGenreRequest) GetGenreId() string {
	if x != nil {
		return x.GenreId
	}
	return ""
}

func (x *UpdateGenreRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGenreRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateGenreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Genre         *GenreData             `protobuf:"bytes,1,opt,name=genre,proto3" json:"genre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGenreResponse) Reset() {
	*x = UpdateGenreResponse{}
	mi := &file_proto_genre_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGenreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGenreResponse) ProtoMessage() {}

func (x *UpdateGenreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_genre_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGenreResponse.ProtoReflect.Descriptor instead.
func (*UpdateGenreResponse) Descriptor() ([]byte, []int) {
	return file_proto_genre_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateGenreResponse) GetGenre() *GenreData {
	if x != nil {
		return x.Genre
	}
	return nil
}

type DeleteGenreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GenreId       string                 `protobuf:"bytes,1,opt,name=genre_id,json=genreId,proto3" json:"genre_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGenreRequest) Reset() {
	*x = DeleteGenreRequest{}
	mi := &file_proto_genre_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGenreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGenreRequest) ProtoMessage() {}

func (x *DeleteGenreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_genre_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGenreRequest.ProtoReflect.Descriptor instead.
func (*DeleteGenreRequest) Descriptor() ([]byte, []int) {
	return file_proto_genre_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteGenreRequest) GetGenreId() string {
	if x != nil {
		return x.GenreId
	}
	return ""
}

type DeleteGenreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGenreResponse) Reset() {
	*x = DeleteGenreResponse{}
	mi := &file_proto_genre_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGenreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGenreResponse) ProtoMessage() {}

func (x *DeleteGenreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_genre_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGenreResponse.ProtoReflect.Descriptor instead.
func (*DeleteGenreResponse) Descriptor() ([]byte, []int) {
	return file_proto_genre_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteGenreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Errors        map[string]string      `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_proto_genre_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_genre_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_proto_genre_proto_rawDescGZIP(), []int{11}
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResponse) GetErrors() map[string]string {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_proto_genre_proto protoreflect.FileDescriptor

const file_proto_genre_proto_rawDesc = "" +
	"\n" +
	"\x11proto/genre.proto\x12\x05genre\"p\n" +
	"\tGenreData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"M\n" +
	"\rGetAllRequest\x12\x1f\n" +
	"\vpage_number\x18\x01 \x01(\x05R\n" +
	"pageNumber\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"q\n" +
	"\x0eGetAllResponse\x12(\n" +
	"\x06genres\x18\x01 \x03(\v2\x10.genre.GenreDataR\x06genres\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x1f\n" +
	"\vtotal_pages\x18\x03 \x01(\x05R\n" +
	"totalPages\",\n" +
	"\x0fGetGenreRequest\x12\x19\n" +
	"\bgenre_id\x18\x01 \x01(\tR\agenreId\":\n" +
	"\x10GetGenreResponse\x12&\n" +
	"\x05genre\x18\x01 \x01(\v2\x10.genre.GenreDataR\x05genre\"J\n" +
	"\x12CreateGenreRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"W\n" +
	"\x13CreateGenreResponse\x12&\n" +
	"\x05genre\x18\x01 \x01(\v2\x10.genre.GenreDataR\x05genre\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"e\n" +
	"\x12UpdateGenreRequest\x12\x19\n" +
	"\bgenre_id\x18\x01 \x01(\tR\agenreId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"=\n" +
	"\x13UpdateGenreResponse\x12&\n" +
	"\x05genre\x18\x01 \x01(\v2\x10.genre.GenreDataR\x05genre\"/\n" +
	"\x12DeleteGenreRequest\x12\x19\n" +
	"\bgenre_id\x18\x01 \x01(\tR\agenreId\"/\n" +
	"\x13DeleteGenreResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x9e\x01\n" +
	"\rErrorResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x128\n" +
	"\x06errors\x18\x02 \x03(\v2 .genre.ErrorResponse.ErrorsEntryR\x06errors\x1a9\n" +
	"\vErrorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xd4\x02\n" +
	"\fGenreService\x12D\n" +
	"\vCreateGenre\x12\x19.genre.CreateGenreRequest\x1a\x1a.genre.CreateGenreResponse\x125\n" +
	"\x06GetAll\x12\x14.genre.GetAllRequest\x1a\x15.genre.GetAllResponse\x12;\n" +
	"\bGetGenre\x12\x16.genre.GetGenreRequest\x1a\x17.genre.GetGenreResponse\x12D\n" +
	"\vUpdateGenre\x12\x19.genre.UpdateGenreRequest\x1a\x1a.genre.UpdateGenreResponse\x12D\n" +
	"\vDeleteGenre\x12\x19.genre.DeleteGenreRequest\x1a\x1a.genre.DeleteGenreResponseBKZIgithub.com/Ostap00034/siproject-beercut-backend/genre-service/proto;genreb\x06proto3"

var (
	file_proto_genre_proto_rawDescOnce sync.Once
	file_proto_genre_proto_rawDescData []byte
)

func file_proto_genre_proto_rawDescGZIP() []byte {
	file_proto_genre_proto_rawDescOnce.Do(func() {
		file_proto_genre_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_genre_proto_rawDesc), len(file_proto_genre_proto_rawDesc)))
	})
	return file_proto_genre_proto_rawDescData
}

var file_proto_genre_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_genre_proto_goTypes = []any{
	(*GenreData)(nil),           // 0: genre.GenreData
	(*GetAllRequest)(nil),       // 1: genre.GetAllRequest
	(*GetAllResponse)(nil),      // 2: genre.GetAllResponse
	(*GetGenreRequest)(nil),     // 3: genre.GetGenreRequest
	(*GetGenreResponse)(nil),    // 4: genre.GetGenreResponse
	(*CreateGenreRequest)(nil),  // 5: genre.CreateGenreRequest
	(*CreateGenreResponse)(nil), // 6: genre.CreateGenreResponse
	(*UpdateGenreRequest)(nil),  // 7: genre.UpdateGenreRequest
	(*UpdateGenreResponse)(nil), // 8: genre.UpdateGenreResponse
	(*DeleteGenreRequest)(nil),  // 9: genre.DeleteGenreRequest
	(*DeleteGenreResponse)(nil), // 10: genre.DeleteGenreResponse
	(*ErrorResponse)(nil),       // 11: genre.ErrorResponse
	nil,                         // 12: genre.ErrorResponse.ErrorsEntry
}
var file_proto_genre_proto_depIdxs = []int32{
	0,  // 0: genre.GetAllResponse.genres:type_name -> genre.GenreData
	0,  // 1: genre.GetGenreResponse.genre:type_name -> genre.GenreData
	0,  // 2: genre.CreateGenreResponse.genre:type_name -> genre.GenreData
	0,  // 3: genre.UpdateGenreResponse.genre:type_name -> genre.GenreData
	12, // 4: genre.ErrorResponse.errors:type_name -> genre.ErrorResponse.ErrorsEntry
	5,  // 5: genre.GenreService.CreateGenre:input_type -> genre.CreateGenreRequest
	1,  // 6: genre.GenreService.GetAll:input_type -> genre.GetAllRequest
	3,  // 7: genre.GenreService.GetGenre:input_type -> genre.GetGenreRequest
	7,  // 8: genre.GenreService.UpdateGenre:input_type -> genre.UpdateGenreRequest
	9,  // 9: genre.GenreService.DeleteGenre:input_type -> genre.DeleteGenreRequest
	6,  // 10: genre.GenreService.CreateGenre:output_type -> genre.CreateGenreResponse
	2,  // 11: genre.GenreService.GetAll:output_type -> genre.GetAllResponse
	4,  // 12: genre.GenreService.GetGenre:output_type -> genre.GetGenreResponse
	8,  // 13: genre.GenreService.UpdateGenre:output_type -> genre.UpdateGenreResponse
	10, // 14: genre.GenreService.DeleteGenre:output_type -> genre.DeleteGenreResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_genre_proto_init() }
func file_proto_genre_proto_init() {
	if File_proto_genre_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_genre_proto_rawDesc), len(file_proto_genre_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_genre_proto_goTypes,
		DependencyIndexes: file_proto_genre_proto_depIdxs,
		MessageInfos:      file_proto_genre_proto_msgTypes,
	}.Build()
	File_proto_genre_proto = out.File
	file_proto_genre_proto_goTypes = nil
	file_proto_genre_proto_depIdxs = nil
}
