// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MovementHistoriesColumns holds the columns for the "movement_histories" table.
	MovementHistoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "picture_id", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeString},
		{Name: "from", Type: field.TypeEnum, Enums: []string{"IN_STORAGE", "IN_EXHIBITION", "IN_RESTORATION"}},
		{Name: "to", Type: field.TypeEnum, Enums: []string{"IN_STORAGE", "IN_EXHIBITION", "IN_RESTORATION"}},
		{Name: "created_at", Type: field.TypeTime},
	}
	// MovementHistoriesTable holds the schema information for the "movement_histories" table.
	MovementHistoriesTable = &schema.Table{
		Name:       "movement_histories",
		Columns:    MovementHistoriesColumns,
		PrimaryKey: []*schema.Column{MovementHistoriesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MovementHistoriesTable,
	}
)

func init() {
}
