// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ExhibitionsColumns holds the columns for the "exhibitions" table.
	ExhibitionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString},
		{Name: "pictures_ids", Type: field.TypeJSON, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"OPENED", "CLOSED"}, Default: "CLOSED"},
		{Name: "created_at", Type: field.TypeTime},
	}
	// ExhibitionsTable holds the schema information for the "exhibitions" table.
	ExhibitionsTable = &schema.Table{
		Name:       "exhibitions",
		Columns:    ExhibitionsColumns,
		PrimaryKey: []*schema.Column{ExhibitionsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ExhibitionsTable,
	}
)

func init() {
}
