// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Exhibition is the predicate function for exhibition builders.
type Exhibition func(*sql.Selector)
