// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Ostap00034/siproject-beercut-backend/exhibition-service/ent/exhibition"
	"github.com/Ostap00034/siproject-beercut-backend/exhibition-service/ent/predicate"
)

// ExhibitionDelete is the builder for deleting a Exhibition entity.
type ExhibitionDelete struct {
	config
	hooks    []Hook
	mutation *ExhibitionMutation
}

// Where appends a list predicates to the ExhibitionDelete builder.
func (ed *ExhibitionDelete) Where(ps ...predicate.Exhibition) *ExhibitionDelete {
	ed.mutation.Where(ps...)
	return ed
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ed *ExhibitionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ed.sqlExec, ed.mutation, ed.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ed *ExhibitionDelete) ExecX(ctx context.Context) int {
	n, err := ed.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ed *ExhibitionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(exhibition.Table, sqlgraph.NewFieldSpec(exhibition.FieldID, field.TypeInt))
	if ps := ed.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ed.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ed.mutation.done = true
	return affected, err
}

// ExhibitionDeleteOne is the builder for deleting a single Exhibition entity.
type ExhibitionDeleteOne struct {
	ed *ExhibitionDelete
}

// Where appends a list predicates to the ExhibitionDelete builder.
func (edo *ExhibitionDeleteOne) Where(ps ...predicate.Exhibition) *ExhibitionDeleteOne {
	edo.ed.mutation.Where(ps...)
	return edo
}

// Exec executes the deletion query.
func (edo *ExhibitionDeleteOne) Exec(ctx context.Context) error {
	n, err := edo.ed.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{exhibition.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (edo *ExhibitionDeleteOne) ExecX(ctx context.Context) {
	if err := edo.Exec(ctx); err != nil {
		panic(err)
	}
}
