// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Ostap00034/siproject-beercut-backend/exhibition-service/ent/exhibition"
	"github.com/Ostap00034/siproject-beercut-backend/exhibition-service/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	exhibitionFields := schema.Exhibition{}.Fields()
	_ = exhibitionFields
	// exhibitionDescName is the schema descriptor for name field.
	exhibitionDescName := exhibitionFields[0].Descriptor()
	// exhibition.NameValidator is a validator for the "name" field. It is called by the builders before save.
	exhibition.NameValidator = exhibitionDescName.Validators[0].(func(string) error)
	// exhibitionDescCreatedAt is the schema descriptor for created_at field.
	exhibitionDescCreatedAt := exhibitionFields[4].Descriptor()
	// exhibition.DefaultCreatedAt holds the default value on creation for the created_at field.
	exhibition.DefaultCreatedAt = exhibitionDescCreatedAt.Default.(func() time.Time)
}
