// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Ostap00034/siproject-beercut-backend/author-service/ent/author"
	"github.com/Ostap00034/siproject-beercut-backend/author-service/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	authorFields := schema.Author{}.Fields()
	_ = authorFields
	// authorDescCreatedAt is the schema descriptor for created_at field.
	authorDescCreatedAt := authorFields[3].Descriptor()
	// author.DefaultCreatedAt holds the default value on creation for the created_at field.
	author.DefaultCreatedAt = authorDescCreatedAt.Default.(time.Time)
}
