// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Ostap00034/siproject-beercut-backend/movementhistory-service/ent/movementhistory"
	"github.com/Ostap00034/siproject-beercut-backend/movementhistory-service/ent/predicate"
)

// MovementHistoryDelete is the builder for deleting a MovementHistory entity.
type MovementHistoryDelete struct {
	config
	hooks    []Hook
	mutation *MovementHistoryMutation
}

// Where appends a list predicates to the MovementHistoryDelete builder.
func (mhd *MovementHistoryDelete) Where(ps ...predicate.MovementHistory) *MovementHistoryDelete {
	mhd.mutation.Where(ps...)
	return mhd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mhd *MovementHistoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, mhd.sqlExec, mhd.mutation, mhd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mhd *MovementHistoryDelete) ExecX(ctx context.Context) int {
	n, err := mhd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mhd *MovementHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(movementhistory.Table, sqlgraph.NewFieldSpec(movementhistory.FieldID, field.TypeInt))
	if ps := mhd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mhd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mhd.mutation.done = true
	return affected, err
}

// MovementHistoryDeleteOne is the builder for deleting a single MovementHistory entity.
type MovementHistoryDeleteOne struct {
	mhd *MovementHistoryDelete
}

// Where appends a list predicates to the MovementHistoryDelete builder.
func (mhdo *MovementHistoryDeleteOne) Where(ps ...predicate.MovementHistory) *MovementHistoryDeleteOne {
	mhdo.mhd.mutation.Where(ps...)
	return mhdo
}

// Exec executes the deletion query.
func (mhdo *MovementHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := mhdo.mhd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{movementhistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mhdo *MovementHistoryDeleteOne) ExecX(ctx context.Context) {
	if err := mhdo.Exec(ctx); err != nil {
		panic(err)
	}
}
