// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Ostap00034/siproject-beercut-backend/movementhistory-service/ent/movementhistory"
	"github.com/Ostap00034/siproject-beercut-backend/movementhistory-service/ent/predicate"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeMovementHistory = "MovementHistory"
)

// MovementHistoryMutation represents an operation that mutates the MovementHistory nodes in the graph.
type MovementHistoryMutation struct {
	config
	op            Op
	typ           string
	id            *int
	picture_id    *string
	user_id       *string
	from          *movementhistory.From
	to            *movementhistory.To
	created_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*MovementHistory, error)
	predicates    []predicate.MovementHistory
}

var _ ent.Mutation = (*MovementHistoryMutation)(nil)

// movementhistoryOption allows management of the mutation configuration using functional options.
type movementhistoryOption func(*MovementHistoryMutation)

// newMovementHistoryMutation creates new mutation for the MovementHistory entity.
func newMovementHistoryMutation(c config, op Op, opts ...movementhistoryOption) *MovementHistoryMutation {
	m := &MovementHistoryMutation{
		config:        c,
		op:            op,
		typ:           TypeMovementHistory,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withMovementHistoryID sets the ID field of the mutation.
func withMovementHistoryID(id int) movementhistoryOption {
	return func(m *MovementHistoryMutation) {
		var (
			err   error
			once  sync.Once
			value *MovementHistory
		)
		m.oldValue = func(ctx context.Context) (*MovementHistory, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().MovementHistory.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withMovementHistory sets the old MovementHistory of the mutation.
func withMovementHistory(node *MovementHistory) movementhistoryOption {
	return func(m *MovementHistoryMutation) {
		m.oldValue = func(context.Context) (*MovementHistory, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m MovementHistoryMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m MovementHistoryMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *MovementHistoryMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *MovementHistoryMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().MovementHistory.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetPictureID sets the "picture_id" field.
func (m *MovementHistoryMutation) SetPictureID(s string) {
	m.picture_id = &s
}

// PictureID returns the value of the "picture_id" field in the mutation.
func (m *MovementHistoryMutation) PictureID() (r string, exists bool) {
	v := m.picture_id
	if v == nil {
		return
	}
	return *v, true
}

// OldPictureID returns the old "picture_id" field's value of the MovementHistory entity.
// If the MovementHistory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MovementHistoryMutation) OldPictureID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPictureID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPictureID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPictureID: %w", err)
	}
	return oldValue.PictureID, nil
}

// ResetPictureID resets all changes to the "picture_id" field.
func (m *MovementHistoryMutation) ResetPictureID() {
	m.picture_id = nil
}

// SetUserID sets the "user_id" field.
func (m *MovementHistoryMutation) SetUserID(s string) {
	m.user_id = &s
}

// UserID returns the value of the "user_id" field in the mutation.
func (m *MovementHistoryMutation) UserID() (r string, exists bool) {
	v := m.user_id
	if v == nil {
		return
	}
	return *v, true
}

// OldUserID returns the old "user_id" field's value of the MovementHistory entity.
// If the MovementHistory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MovementHistoryMutation) OldUserID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserID: %w", err)
	}
	return oldValue.UserID, nil
}

// ResetUserID resets all changes to the "user_id" field.
func (m *MovementHistoryMutation) ResetUserID() {
	m.user_id = nil
}

// SetFrom sets the "from" field.
func (m *MovementHistoryMutation) SetFrom(value movementhistory.From) {
	m.from = &value
}

// From returns the value of the "from" field in the mutation.
func (m *MovementHistoryMutation) From() (r movementhistory.From, exists bool) {
	v := m.from
	if v == nil {
		return
	}
	return *v, true
}

// OldFrom returns the old "from" field's value of the MovementHistory entity.
// If the MovementHistory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MovementHistoryMutation) OldFrom(ctx context.Context) (v movementhistory.From, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFrom is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFrom requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFrom: %w", err)
	}
	return oldValue.From, nil
}

// ResetFrom resets all changes to the "from" field.
func (m *MovementHistoryMutation) ResetFrom() {
	m.from = nil
}

// SetTo sets the "to" field.
func (m *MovementHistoryMutation) SetTo(value movementhistory.To) {
	m.to = &value
}

// To returns the value of the "to" field in the mutation.
func (m *MovementHistoryMutation) To() (r movementhistory.To, exists bool) {
	v := m.to
	if v == nil {
		return
	}
	return *v, true
}

// OldTo returns the old "to" field's value of the MovementHistory entity.
// If the MovementHistory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MovementHistoryMutation) OldTo(ctx context.Context) (v movementhistory.To, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTo is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTo requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTo: %w", err)
	}
	return oldValue.To, nil
}

// ResetTo resets all changes to the "to" field.
func (m *MovementHistoryMutation) ResetTo() {
	m.to = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *MovementHistoryMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *MovementHistoryMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the MovementHistory entity.
// If the MovementHistory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MovementHistoryMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *MovementHistoryMutation) ResetCreatedAt() {
	m.created_at = nil
}

// Where appends a list predicates to the MovementHistoryMutation builder.
func (m *MovementHistoryMutation) Where(ps ...predicate.MovementHistory) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the MovementHistoryMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *MovementHistoryMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.MovementHistory, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *MovementHistoryMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *MovementHistoryMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (MovementHistory).
func (m *MovementHistoryMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *MovementHistoryMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.picture_id != nil {
		fields = append(fields, movementhistory.FieldPictureID)
	}
	if m.user_id != nil {
		fields = append(fields, movementhistory.FieldUserID)
	}
	if m.from != nil {
		fields = append(fields, movementhistory.FieldFrom)
	}
	if m.to != nil {
		fields = append(fields, movementhistory.FieldTo)
	}
	if m.created_at != nil {
		fields = append(fields, movementhistory.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *MovementHistoryMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case movementhistory.FieldPictureID:
		return m.PictureID()
	case movementhistory.FieldUserID:
		return m.UserID()
	case movementhistory.FieldFrom:
		return m.From()
	case movementhistory.FieldTo:
		return m.To()
	case movementhistory.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *MovementHistoryMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case movementhistory.FieldPictureID:
		return m.OldPictureID(ctx)
	case movementhistory.FieldUserID:
		return m.OldUserID(ctx)
	case movementhistory.FieldFrom:
		return m.OldFrom(ctx)
	case movementhistory.FieldTo:
		return m.OldTo(ctx)
	case movementhistory.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown MovementHistory field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *MovementHistoryMutation) SetField(name string, value ent.Value) error {
	switch name {
	case movementhistory.FieldPictureID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPictureID(v)
		return nil
	case movementhistory.FieldUserID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserID(v)
		return nil
	case movementhistory.FieldFrom:
		v, ok := value.(movementhistory.From)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFrom(v)
		return nil
	case movementhistory.FieldTo:
		v, ok := value.(movementhistory.To)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTo(v)
		return nil
	case movementhistory.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown MovementHistory field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *MovementHistoryMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *MovementHistoryMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *MovementHistoryMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown MovementHistory numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *MovementHistoryMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *MovementHistoryMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *MovementHistoryMutation) ClearField(name string) error {
	return fmt.Errorf("unknown MovementHistory nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *MovementHistoryMutation) ResetField(name string) error {
	switch name {
	case movementhistory.FieldPictureID:
		m.ResetPictureID()
		return nil
	case movementhistory.FieldUserID:
		m.ResetUserID()
		return nil
	case movementhistory.FieldFrom:
		m.ResetFrom()
		return nil
	case movementhistory.FieldTo:
		m.ResetTo()
		return nil
	case movementhistory.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown MovementHistory field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *MovementHistoryMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *MovementHistoryMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *MovementHistoryMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *MovementHistoryMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *MovementHistoryMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *MovementHistoryMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *MovementHistoryMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown MovementHistory unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *MovementHistoryMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown MovementHistory edge %s", name)
}
