// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Ostap00034/siproject-beercut-backend/genre-service/ent/genre"
	"github.com/Ostap00034/siproject-beercut-backend/genre-service/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	genreFields := schema.Genre{}.Fields()
	_ = genreFields
	// genreDescDescription is the schema descriptor for description field.
	genreDescDescription := genreFields[1].Descriptor()
	// genre.DefaultDescription holds the default value on creation for the description field.
	genre.DefaultDescription = genreDescDescription.Default.(string)
	// genreDescCreatedAt is the schema descriptor for created_at field.
	genreDescCreatedAt := genreFields[2].Descriptor()
	// genre.DefaultCreatedAt holds the default value on creation for the created_at field.
	genre.DefaultCreatedAt = genreDescCreatedAt.Default.(time.Time)
}
