// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/author.proto

package author

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,3,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	DateOfDeath   string                 `protobuf:"bytes,4,opt,name=date_of_death,json=dateOfDeath,proto3" json:"date_of_death,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorData) Reset() {
	*x = AuthorData{}
	mi := &file_proto_author_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorData) ProtoMessage() {}

func (x *AuthorData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_author_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorData.ProtoReflect.Descriptor instead.
func (*AuthorData) Descriptor() ([]byte, []int) {
	return file_proto_author_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuthorData) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *AuthorData) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *AuthorData) GetDateOfDeath() string {
	if x != nil {
		return x.DateOfDeath
	}
	return ""
}

func (x *AuthorData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_proto_author_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_author_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_proto_author_proto_rawDescGZIP(), []int{1}
}

type GetAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authors       []*AuthorData          `protobuf:"bytes,1,rep,name=authors,proto3" json:"authors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	mi := &file_proto_author_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_author_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse.ProtoReflect.Descriptor instead.
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return file_proto_author_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllResponse) GetAuthors() []*AuthorData {
	if x != nil {
		return x.Authors
	}
	return nil
}

type GetAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      string                 `protobuf:"bytes,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorRequest) Reset() {
	*x = GetAuthorRequest{}
	mi := &file_proto_author_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorRequest) ProtoMessage() {}

func (x *GetAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_author_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorRequest.ProtoReflect.Descriptor instead.
func (*GetAuthorRequest) Descriptor() ([]byte, []int) {
	return file_proto_author_proto_rawDescGZIP(), []int{3}
}

func (x *GetAuthorRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

type GetAuthorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        *AuthorData            `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorResponse) Reset() {
	*x = GetAuthorResponse{}
	mi := &file_proto_author_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorResponse) ProtoMessage() {}

func (x *GetAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_author_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorResponse.ProtoReflect.Descriptor instead.
func (*GetAuthorResponse) Descriptor() ([]byte, []int) {
	return file_proto_author_proto_rawDescGZIP(), []int{4}
}

func (x *GetAuthorResponse) GetAuthor() *AuthorData {
	if x != nil {
		return x.Author
	}
	return nil
}

type CreateAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,2,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	DateOfDeath   string                 `protobuf:"bytes,3,opt,name=date_of_death,json=dateOfDeath,proto3" json:"date_of_death,omitempty"` // Поле необязательно, если значение не установлено, оно будет пустым.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuthorRequest) Reset() {
	*x = CreateAuthorRequest{}
	mi := &file_proto_author_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuthorRequest) ProtoMessage() {}

func (x *CreateAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_author_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuthorRequest.ProtoReflect.Descriptor instead.
func (*CreateAuthorRequest) Descriptor() ([]byte, []int) {
	return file_proto_author_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAuthorRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateAuthorRequest) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *CreateAuthorRequest) GetDateOfDeath() string {
	if x != nil {
		return x.DateOfDeath
	}
	return ""
}

type CreateAuthorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        *AuthorData            `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Рекомендуется "Автор успешно создан"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuthorResponse) Reset() {
	*x = CreateAuthorResponse{}
	mi := &file_proto_author_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuthorResponse) ProtoMessage() {}

func (x *CreateAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_author_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuthorResponse.ProtoReflect.Descriptor instead.
func (*CreateAuthorResponse) Descriptor() ([]byte, []int) {
	return file_proto_author_proto_rawDescGZIP(), []int{6}
}

func (x *CreateAuthorResponse) GetAuthor() *AuthorData {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *CreateAuthorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      string                 `protobuf:"bytes,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,3,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	DateOfDeath   string                 `protobuf:"bytes,4,opt,name=date_of_death,json=dateOfDeath,proto3" json:"date_of_death,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAuthorRequest) Reset() {
	*x = UpdateAuthorRequest{}
	mi := &file_proto_author_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAuthorRequest) ProtoMessage() {}

func (x *UpdateAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_author_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAuthorRequest.ProtoReflect.Descriptor instead.
func (*UpdateAuthorRequest) Descriptor() ([]byte, []int) {
	return file_proto_author_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAuthorRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *UpdateAuthorRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UpdateAuthorRequest) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *UpdateAuthorRequest) GetDateOfDeath() string {
	if x != nil {
		return x.DateOfDeath
	}
	return ""
}

type UpdateAuthorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        *AuthorData            `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAuthorResponse) Reset() {
	*x = UpdateAuthorResponse{}
	mi := &file_proto_author_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAuthorResponse) ProtoMessage() {}

func (x *UpdateAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_author_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAuthorResponse.ProtoReflect.Descriptor instead.
func (*UpdateAuthorResponse) Descriptor() ([]byte, []int) {
	return file_proto_author_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAuthorResponse) GetAuthor() *AuthorData {
	if x != nil {
		return x.Author
	}
	return nil
}

type DeleteAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      string                 `protobuf:"bytes,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAuthorRequest) Reset() {
	*x = DeleteAuthorRequest{}
	mi := &file_proto_author_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAuthorRequest) ProtoMessage() {}

func (x *DeleteAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_author_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAuthorRequest.ProtoReflect.Descriptor instead.
func (*DeleteAuthorRequest) Descriptor() ([]byte, []int) {
	return file_proto_author_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteAuthorRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

type DeleteAuthorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAuthorResponse) Reset() {
	*x = DeleteAuthorResponse{}
	mi := &file_proto_author_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAuthorResponse) ProtoMessage() {}

func (x *DeleteAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_author_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAuthorResponse.ProtoReflect.Descriptor instead.
func (*DeleteAuthorResponse) Descriptor() ([]byte, []int) {
	return file_proto_author_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteAuthorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Errors        map[string]string      `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_proto_author_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_author_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_proto_author_proto_rawDescGZIP(), []int{11}
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResponse) GetErrors() map[string]string {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_proto_author_proto protoreflect.FileDescriptor

const file_proto_author_proto_rawDesc = "" +
	"\n" +
	"\x12proto/author.proto\x12\x06author\"\xa0\x01\n" +
	"\n" +
	"AuthorData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\"\n" +
	"\rdate_of_birth\x18\x03 \x01(\tR\vdateOfBirth\x12\"\n" +
	"\rdate_of_death\x18\x04 \x01(\tR\vdateOfDeath\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\x0f\n" +
	"\rGetAllRequest\">\n" +
	"\x0eGetAllResponse\x12,\n" +
	"\aauthors\x18\x01 \x03(\v2\x12.author.AuthorDataR\aauthors\"/\n" +
	"\x10GetAuthorRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\tR\bauthorId\"?\n" +
	"\x11GetAuthorResponse\x12*\n" +
	"\x06author\x18\x01 \x01(\v2\x12.author.AuthorDataR\x06author\"z\n" +
	"\x13CreateAuthorRequest\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\x12\"\n" +
	"\rdate_of_birth\x18\x02 \x01(\tR\vdateOfBirth\x12\"\n" +
	"\rdate_of_death\x18\x03 \x01(\tR\vdateOfDeath\"\\\n" +
	"\x14CreateAuthorResponse\x12*\n" +
	"\x06author\x18\x01 \x01(\v2\x12.author.AuthorDataR\x06author\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x97\x01\n" +
	"\x13UpdateAuthorRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\tR\bauthorId\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\"\n" +
	"\rdate_of_birth\x18\x03 \x01(\tR\vdateOfBirth\x12\"\n" +
	"\rdate_of_death\x18\x04 \x01(\tR\vdateOfDeath\"B\n" +
	"\x14UpdateAuthorResponse\x12*\n" +
	"\x06author\x18\x01 \x01(\v2\x12.author.AuthorDataR\x06author\"2\n" +
	"\x13DeleteAuthorRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\tR\bauthorId\"0\n" +
	"\x14DeleteAuthorResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x9f\x01\n" +
	"\rErrorResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x129\n" +
	"\x06errors\x18\x02 \x03(\v2!.author.ErrorResponse.ErrorsEntryR\x06errors\x1a9\n" +
	"\vErrorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xeb\x02\n" +
	"\rAuthorService\x12I\n" +
	"\fCreateAuthor\x12\x1b.author.CreateAuthorRequest\x1a\x1c.author.CreateAuthorResponse\x127\n" +
	"\x06GetAll\x12\x15.author.GetAllRequest\x1a\x16.author.GetAllResponse\x12@\n" +
	"\tGetAuthor\x12\x18.author.GetAuthorRequest\x1a\x19.author.GetAuthorResponse\x12I\n" +
	"\fUpdateAuthor\x12\x1b.author.UpdateAuthorRequest\x1a\x1c.author.UpdateAuthorResponse\x12I\n" +
	"\fDeleteAuthor\x12\x1b.author.DeleteAuthorRequest\x1a\x1c.author.DeleteAuthorResponseBMZKgithub.com/Ostap00034/siproject-beercut-backend/author-service/proto;authorb\x06proto3"

var (
	file_proto_author_proto_rawDescOnce sync.Once
	file_proto_author_proto_rawDescData []byte
)

func file_proto_author_proto_rawDescGZIP() []byte {
	file_proto_author_proto_rawDescOnce.Do(func() {
		file_proto_author_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_author_proto_rawDesc), len(file_proto_author_proto_rawDesc)))
	})
	return file_proto_author_proto_rawDescData
}

var file_proto_author_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_author_proto_goTypes = []any{
	(*AuthorData)(nil),           // 0: author.AuthorData
	(*GetAllRequest)(nil),        // 1: author.GetAllRequest
	(*GetAllResponse)(nil),       // 2: author.GetAllResponse
	(*GetAuthorRequest)(nil),     // 3: author.GetAuthorRequest
	(*GetAuthorResponse)(nil),    // 4: author.GetAuthorResponse
	(*CreateAuthorRequest)(nil),  // 5: author.CreateAuthorRequest
	(*CreateAuthorResponse)(nil), // 6: author.CreateAuthorResponse
	(*UpdateAuthorRequest)(nil),  // 7: author.UpdateAuthorRequest
	(*UpdateAuthorResponse)(nil), // 8: author.UpdateAuthorResponse
	(*DeleteAuthorRequest)(nil),  // 9: author.DeleteAuthorRequest
	(*DeleteAuthorResponse)(nil), // 10: author.DeleteAuthorResponse
	(*ErrorResponse)(nil),        // 11: author.ErrorResponse
	nil,                          // 12: author.ErrorResponse.ErrorsEntry
}
var file_proto_author_proto_depIdxs = []int32{
	0,  // 0: author.GetAllResponse.authors:type_name -> author.AuthorData
	0,  // 1: author.GetAuthorResponse.author:type_name -> author.AuthorData
	0,  // 2: author.CreateAuthorResponse.author:type_name -> author.AuthorData
	0,  // 3: author.UpdateAuthorResponse.author:type_name -> author.AuthorData
	12, // 4: author.ErrorResponse.errors:type_name -> author.ErrorResponse.ErrorsEntry
	5,  // 5: author.AuthorService.CreateAuthor:input_type -> author.CreateAuthorRequest
	1,  // 6: author.AuthorService.GetAll:input_type -> author.GetAllRequest
	3,  // 7: author.AuthorService.GetAuthor:input_type -> author.GetAuthorRequest
	7,  // 8: author.AuthorService.UpdateAuthor:input_type -> author.UpdateAuthorRequest
	9,  // 9: author.AuthorService.DeleteAuthor:input_type -> author.DeleteAuthorRequest
	6,  // 10: author.AuthorService.CreateAuthor:output_type -> author.CreateAuthorResponse
	2,  // 11: author.AuthorService.GetAll:output_type -> author.GetAllResponse
	4,  // 12: author.AuthorService.GetAuthor:output_type -> author.GetAuthorResponse
	8,  // 13: author.AuthorService.UpdateAuthor:output_type -> author.UpdateAuthorResponse
	10, // 14: author.AuthorService.DeleteAuthor:output_type -> author.DeleteAuthorResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_author_proto_init() }
func file_proto_author_proto_init() {
	if File_proto_author_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_author_proto_rawDesc), len(file_proto_author_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_author_proto_goTypes,
		DependencyIndexes: file_proto_author_proto_depIdxs,
		MessageInfos:      file_proto_author_proto_msgTypes,
	}.Build()
	File_proto_author_proto = out.File
	file_proto_author_proto_goTypes = nil
	file_proto_author_proto_depIdxs = nil
}
